export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCSESS: 'FETCH_CATEGORIES_SUCSESS',
    FETCH_CATEGORIES_FAIL: 'FETCH_CATEGORIES_FAIL',
}